@baseUrl = http://localhost:3011
@token = {{createToken.response.body.$.token}}
@userId = 1
@password = "123456"

# @name getAll
GET {{baseUrl}}/users HTTP/1.1
###


# @name getUserById
GET {{baseUrl}}/users/{{userId}} HTTP/1.1
###

# @name createToken
POST {{baseUrl}}/users/{{userId}}/token HTTP/1.1
Content-Type: application/json

{
    "password": {{password}}
}
###


# @name updateUser 
PUT {{baseUrl}}/users/{{userId}} HTTP/1.1
Content-Type: application/json

{
  "address":"localhost",
  "port":10086
}
###

